db_uri: mongodb://mongo.open5gs.svc.cluster.local/open5gs
logger:
  file:
    path: /var/log/open5gs/pcf.log

global:
  max:
    ue: 1024

pcf:
  sbi:
    server:
      - address: 0.0.0.0
        port: 7777
    client:
      scp:
        - uri: http://open5gs-scp.open5gs.svc.cluster.local:7777
  metrics:
    server:
      - address: 0.0.0.0
        port: 9090
